# Generated by Django 3.2.12 on 2022-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diak',
            name='diakigazolvanyszam',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='diakneve',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='elertpontszam',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='felvetteke',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
