# Generated by Django 3.2.12 on 2022-04-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20220325_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iskola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskola_diakigazolvanyszam', models.IntegerField()),
                ('iskola', models.TextField()),
            ],
            options={
                'verbose_name': 'Iskola',
                'verbose_name_plural': 'Iskolas',
            },
        ),
        migrations.AddField(
            model_name='diak',
            name='iskola',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='APP.iskola'),
            preserve_default=False,
        ),
    ]
