# Generated by Django 3.2.12 on 2022-04-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_auto_20220401_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iskola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskola_diakigazolvanyszam', models.IntegerField()),
                ('iskola', models.TextField()),
            ],
            options={
                'verbose_name': 'Iskola',
                'verbose_name_plural': 'Iskolas',
            },
        ),
        migrations.AddField(
            model_name='diak',
            name='diakigazolvanyszam',
            field=models.IntegerField(default=121),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='diakneve',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='elertpontszam',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='felvetteke',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diak',
            name='iskola',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='APP.iskola'),
            preserve_default=False,
        ),
    ]
