# Generated by Django 3.2.12 on 2022-04-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20220401_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diak',
            name='iskola',
        ),
        migrations.DeleteModel(
            name='Iskola',
        ),
    ]
